### ISSUE TITLE
icu tokenizer may panic on invalid UTF-8

### ISSUE THREAD

**Issue by mschoch** [blevesearch/blevex#34]
When the icu tokenizer gets invalid utf8 input like:

```
"something\x96something"
```

You may get a panic.  This seems to depend on the version of ICU you have installed, and may also depend on some default ICU settings and/or environment variables.

Some users have reported that adding the following fixes the issue for them.

```
// #include "unicode/ucnv.h"
func init() {
    C.ucnv_setDefaultName(C.CString("UTF-8"))
}
```

This issue has been moved from the  bleve repo: https://github.com/blevesearch/bleve/issues/185

**Comment by joeblew99** [comment]
same related error maybe ?

````
go get github.com/blevesearch/blevex/icu
# github.com/blevesearch/blevex/icu
../../../blevesearch/blevex/icu/boundary.go:15:11: fatal error: 'unicode/utypes.h' file not found
 #include "unicode/utypes.h"
          ^
1 error generated.

````

**Comment by atthakorn** [comment]
By running    `go test`  in  `github.com/blevesearch/blevex/lang/th`

I see this panic too in my system,

```
panic: runtime error: slice bounds out of range

goroutine 21 [running]:
github.com/blevesearch/blevex/icu.(*UnicodeWordBoundaryTokenizer).Tokenize(0xc4200b4178, 0xc4205dc000, 0x31a, 0x31a, 0x0, 0x0, 0x0)
        /var/www/go/src/github.com/blevesearch/blevex/icu/boundary.go:103 +0x67b
github.com/blevesearch/bleve/analysis.(*Analyzer).Analyze(0xc4200b8780, 0xc4205dc000, 0x31a, 0x31a, 0x31a, 0x31a, 0x7cdf9b7326f47234)
        /var/www/go/src/github.com/blevesearch/bleve/analysis/type.go:86 +0xcc
github.com/blevesearch/bleve/document.(*TextField).Analyze(0xc42052f920, 0xf, 0xc4205628fe)
        /var/www/go/src/github.com/blevesearch/bleve/document/field_text.go:72 +0x86
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Analyze.func1(0x9f6e20, 0xc42052f920, 0x1)
        /var/www/go/src/github.com/blevesearch/bleve/index/upsidedown/analysis.go:48 +0x35b
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Analyze(0xc4201c2300, 0xc42051ca80, 0xc420562f38)
        /var/www/go/src/github.com/blevesearch/bleve/index/upsidedown/analysis.go:70 +0x414
github.com/blevesearch/bleve/index.AnalysisWorker(0xc42008e120, 0xc42008e180)
        /var/www/go/src/github.com/blevesearch/bleve/index/analysis.go:106 +0x55
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
        /var/www/go/src/github.com/blevesearch/bleve/index/analysis.go:94 +0xcd
```

I confirmed the issue is fixed by adding these lines into `blevex/icu/boundary.go`

```
// #include "unicode/ucnv.h"
func init() {
    C.ucnv_setDefaultName(C.CString("UTF-8"))
}
```

@mschoch   Do you have any plan to include this patch into main stream?  It would be really nice, thank you.

**Comment by steveyen** [comment]
Thanks @atthakorn -- wondering if for anybody also running into this and who need a temporary workaround, I'd wonder if those lines of init() code are also just invokable from any app code.
